Force text mode in subprocess
Without this patch, we were obtaining this error due to the change to Python 3.8:

```
INFO:jobrunner:2020-05-06 17:51:35.962457 UTC - Running daily jobs
INFO:jobrunner:Running job 200: `psql -0Atd postgres -c "SELECT datname FROM pg_database WHERE NOT datistemplate AND datname != 'postgres'" | xargs -0tI DB pg_dump --dbname DB --no-owner --no-privileges --file "/mnt/backup/src/DB.sql"`
Traceback (most recent call last):
  File "/etc/periodic/daily/jobrunner", line 77, in <module>
    logging.log(logging.INFO if success else logging.ERROR, "\n".join(log))
TypeError: sequence item 7: expected str instance, bytes found
 ```